FROM ubuntu/yakkety
MAINTAINER nao20010128nao

RUN set -xe && apt-get update && apt-get upgrade -y && apt-get install -y openjdk-8-jdk git tree zip unzip p7zip p7zip-full && rm -rf /var/lib/apt/lists/*
